# Generated by Django 3.1.1 on 2022-01-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lagu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penyanyi', models.CharField(max_length=200)),
                ('cover', models.ImageField(upload_to='')),
                ('music_file', models.FileField(blank=True, null=True, upload_to='')),
                ('music_link', models.CharField(blank=True, max_length=200, null=True)),
                ('durasi', models.CharField(max_length=20)),
            ],
        ),
    ]
