# Generated by Django 3.1.1 on 2022-01-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lagu',
            old_name='music_file',
            new_name='musik_file',
        ),
        migrations.RenameField(
            model_name='lagu',
            old_name='music_link',
            new_name='musik_link',
        ),
    ]
