# Generated by Django 3.1.1 on 2022-01-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_auto_20220120_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lagu',
            old_name='judul',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='lagu',
            old_name='musik_file',
            new_name='audio_file',
        ),
        migrations.RenameField(
            model_name='lagu',
            old_name='musik_link',
            new_name='audio_link',
        ),
        migrations.RenameField(
            model_name='lagu',
            old_name='durasi',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='lagu',
            old_name='cover',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lagu',
            old_name='penyanyi',
            new_name='title',
        ),
    ]
