# Generated by Django 3.1.1 on 2022-01-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20220120_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagu',
            name='artist',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lagu',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
